apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${PROJECT}-${CMD}"
spec:
  template:
    spec:
      containers:
        - name: "${PROJECT}-${CMD}"
          livenessProbe:
            tcpSocket:
              port: $HTTP_PORT
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: $HTTP_PORT
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
