apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT
  namespace: ficool
  labels:
    app: $DEPLOYMENT
    level: "2"
    version: v1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: $DEPLOYMENT
  template:
    metadata:
      labels:
        app: $DEPLOYMENT
        version: v1
    spec:
      containers:
        - name: $DEPLOYMENT
          image: $IMAGE:$VERSION
          command: [ "/app/$PROJECT", "$CMD" ]  # command 和args
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9011
            - name: grpc
              containerPort: 8011
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9011
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9011
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: $DEPLOYMENT
