apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${PROJECT}-${CMD}"
  labels:
    app: "${PROJECT}-${CMD}"
spec:
  selector:
    matchLabels:
      app: "${PROJECT}-${CMD}"
  template:
    metadata:
      labels:
        app: "${PROJECT}-${CMD}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: \"$HTTP_PORT\"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: "${PROJECT}-${CMD}"
          image: $IMAGE_REPO/$PROJECT:$VERSION
          command: [ "/app/$PROJECT", "$CMD" ]
          imagePullPolicy: Always
          ports:
            - name: service
              containerPort: $HTTP_PORT
