apiVersion: v1
kind: Service
metadata:
  name: $SERVICE
  annotations:
  labels:
    app: $SERVICE
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8087
      targetPort: $PORT
  selector:
    app: $SERVICE
