apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT
spec:
  template:
    spec:
      containers:
        - name: $DEPLOYMENT
          livenessProbe:
            tcpSocket:
              port: $PORT
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: $PORT
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
