apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT
  labels:
    app: $DEPLOYMENT
spec:
  selector:
    matchLabels:
      app: $DEPLOYMENT
  template:
    metadata:
      labels:
        app: $DEPLOYMENT
    spec:
      containers:
        - name: $DEPLOYMENT
          image: $IMAGE_REPO/$PROJECT:$VERSION
          command: [ "/app/$PROJECT", "$CMD" ]
          imagePullPolicy: Always
