apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${PROJECT}-${CMD}"
  labels:
    app: "${PROJECT}-${CMD}"
spec:
  selector:
    matchLabels:
      app: "${PROJECT}-${CMD}"
  template:
    metadata:
      labels:
        app: "${PROJECT}-${CMD}"
    spec:
      containers:
        - name: "${PROJECT}-${CMD}"
          image: $IMAGE_REPO/$PROJECT:$VERSION
          command: [ "/app/$PROJECT", "$CMD", "--config=/etc/config/${PROJECT}-${CMD}.yaml" ]
          imagePullPolicy: Always
