apiVersion: batch/v1beta1
kind: Job
metadata:
  name: $JOB
spec:
  template:
    spec:
      containers:
        - name: $JOB
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: log
              mountPath: /log
      volumes:
        - name: config
          configMap:
            name: $JOB
        - name: log
          persistentVolumeClaim:
            claimName: efs-claim