apiVersion: batch/v1
kind: Job
metadata:
  name: "${PROJECT}-${CMD}"
spec:
  template:
    spec:
      containers:
        - name: "${PROJECT}-${CMD}"
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: log
              mountPath: /log
      volumes:
        - name: config
          configMap:
            name: "${PROJECT}-${CMD}"
        - name: log
          persistentVolumeClaim:
            claimName: efs-claim