apiVersion: batch/v1
kind: Job
metadata:
  name: "${PROJECT}-${CMD}"
  labels:
    app: "${PROJECT}-${CMD}"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: "${PROJECT}-${CMD}"
          image: $IMAGE_REPO/$PROJECT:$VERSION
          imagePullPolicy: Always
          command: [ "/app/$PROJECT", "$CMD", "--config=/etc/config/${PROJECT}-${CMD}.yaml" ]
      restartPolicy: Never
