groups:
- name: kafka_health
  rules: 
  #https://github.com/danielqsj/kafka_exporter
  # - alert: KafkaTopicsReplicas
  #   expr: sum(kafka_topic_partition_in_sync_replica) by (topic) < 3
  #   for: 0m
  #   labels:
  #     severity: critical
  #   annotations:
  #     summary: Kafka topics replicas (instance {{ $labels.instance }})
  #     description: "Kafka topic in-sync partition\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: KafkaConsumersGroup
    expr: sum(kafka_consumer_group_ConsumerLagMetrics_Value{groupId!~"amazon.msk.canary.group.broker-1|amazon.msk.canary.group.broker-2|amazon.msk.canary.group.broker-3"}) by (groupId) > 50
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Kafka consumers group (instance {{ $labels.instance }})
      description: "Kafka consumers group\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
