apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${PROJECT}-${CMD}"
spec:
  template:
    spec:
      containers:
        - name: "${PROJECT}-${CMD}"
          resources: # CPU内存限制
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 1
              memory: 2048Mi
