apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "${PROJECT}-${CMD}"
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "${PROJECT}-${CMD}"
              volumeMounts:
                - name: config
                  mountPath: /etc/config
                - name: log
                  mountPath: /log
          volumes:
            - name: config
              configMap:
                name: "${PROJECT}-${CMD}"
            - name: log
              persistentVolumeClaim:
                claimName: efs-claim